#!/bin/bash
# docx-flatten filname.docx
# readlink -f filename.docx > save to bash variable: filepath
# create a timestamp
# mkdir filename-timestamp && cd filename-timestamp
# unzip filepath
# run xproc-script on the folder filename-timestamp
folder="/home/hanson/projects/docx2jats/ocf2jats/sample/sample-unzipped-indented/"
calabash -p folder=$folder docx-flatten.xpl
